# Taken from https://github.com/andyli/HaxeCI/blob/master/appveyor.yml
version: "{build}"

environment:
  global:
    HAXELIB_ROOT: C:\projects\haxelib

install:
  # http://help.appveyor.com/discussions/problems/5616-not-able-to-build-due-to-problem-in-chocolateyinstallps1
  - ps: Set-Service wuauserv -StartupType Manual
  # Install the neko chocolatey package (https://chocolatey.org/packages/neko)
  - cinst neko --version 2.3.0 -y
  # Install the haxe chocolatey package (https://chocolatey.org/packages/haxe)
  - cinst haxe --version 4.1.5 -y
  - RefreshEnv
  # Setup haxelib
  - mkdir "%HAXELIB_ROOT%"
  - haxelib setup "%HAXELIB_ROOT%"
  # Install project dependencies
  - haxelib git lime https://github.com/AlafandyPorting/lime-0.7.3
  - RefreshEnv
  - haxelib install openfl 9.2.2
  - haxelib install flixel 5.2.2
  - haxelib run lime setup flixel
  - haxelib run lime setup
  - haxelib install flixel-tools 1.5.1
  # haxelib run flixel-tools setup -y # Can't do this since it asks [y/n] even with -y argument! Stupid
  - haxelib install flixel-addons 2.11.0
  - haxelib install flixel-ui 2.5.0
  - haxelib install hscript 2.5.0
  - haxelib install flixel-addons 2.11.0
  - haxelib git faxe https://github.com/uhrobots/faxe
  - haxelib install polymod 1.3.1
  - haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
  - haxelib git extension-webm https://github.com/AlafandyPorting/extension-webm
  - haxelib install linc_luajit
  - haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit
  - haxelib run lime rebuild extension-webm windows
  - haxelib install actuate 
  #- haxelib git extension-webm https://github.com/KadeDev/extension-webm
  #- haxelib run lime rebuild extension-webm windows
  #why here's dublicate lmao
  - haxelib list

# No tests idk lol
build_script:
  - haxelib run lime build windows
  # haxelib run lime build linux

artifacts:
  - path: export/release/windows/bin
    name: KadeEngine-Windows
    type: zip
