name: Build

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      os:
        required: true
        type: string
      buildArgs:
        required: true
        type: string
      artifactName:
        required: true
        type: string
      artifactPath:
        required: true
        type: string

env:
  HAXE_VERSION: 4.1.5
  PROJECT_NAME: KadeEngine
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    name: Build
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: ${{ env.HAXE_VERSION }}

      - name: Cache haxelib path
        uses: actions/cache@main
        with:
          path: |
            %HAXELIB_ROOT%
          key: ${{ inputs.os }}-${{ inputs.buildArgs }}

      - name: Update APT
        if: inputs.name == 'Linux'
        run: |
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          sudo apt-get update --fix-missing

      - name: Install libVLC
        if: inputs.name == 'Linux'
        run: sudo apt-get install -y libvlc-dev libvlccore-dev

      - name: Setup XCode
        if: inputs.name == 'iOS'
        uses: maxim-lobanov/setup-xcode@master
        with:
          xcode-version: '16.4'

      - name: Install Libraries
        run: |
          cinst haxe --version 4.1.5 -y
          RefreshEnv
          mkdir "%HAXELIB_ROOT%"
          haxelib setup "%HAXELIB_ROOT%"
          haxelib install lime 7.9.0
          RefreshEnv
          haxelib install openfl
          haxelib install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib install hscript
          haxelib install flixel-addons
          haxelib git faxe https://github.com/uhrobots/faxe
          haxelib git polymod https://github.com/EliteMasterEric/polymod.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git extension-webm https://github.com/KadeDev/extension-webm
          haxelib run lime rebuild extension-webm ${{ inputs.buildArgs }}
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit.git
          haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit
          haxelib install actuate 
          haxelib list

      - name: Configure Android x64
        if: inputs.name == 'Android x64'
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME_17_arm64
          haxelib run lime config ANDROID_SETUP true

      - name: Configure Android x32
        if: inputs.name == 'Android x32'
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME_17_arm64
          haxelib run lime config ANDROID_SETUP true

      - name: Compile
        run: haxelib run lime build ${{ inputs.buildArgs }}

      - name: Make IPA
        if: inputs.name == 'iOS'
        run: |
          cd export/release/ios/build/Release-iphoneos
          mkdir Payload
          mv *.app Payload
          zip -r ${{ env.PROJECT_NAME }}.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: ${{ inputs.artifactName }}
          path: ${{ inputs.artifactPath }}
          if-no-files-found: error
