name: Main

on:
  workflow_dispatch:
    inputs:
      buildAndroid:
        description: 'Build Android targets'
        type: boolean
        default: true
      buildIOS:
        description: 'Build iOS target'
        type: boolean
        default: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  Build:
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows x64
            os: windows-2022
            buildArgs: windows
            artifactName: Windows x64
            artifactPath: export\release\windows\bin\*
          - name: Windows x32
            os: windows-2022
            buildArgs: "windows -32 -D HXCPP_M32 -D 32bits"
            artifactName: Windows x32
            artifactPath: export\32bit\windows\bin\*
          - name: Linux
            os: ubuntu-24.04
            buildArgs: linux
            artifactName: Linux
            artifactPath: export/release/linux/bin/*
          - name: MacOS
            os: macos-15
            buildArgs: mac
            artifactName: MacOS
            artifactPath: export/release/macos/bin/*
          - name: Html5
            os: ubuntu-24.04
            buildArgs: html5
            artifactName: HTML5
            artifactPath: export/release/html5/bin/*
    uses: ./.github/workflows/build.yml
    with:
      name: ${{ matrix.name }}
      os: ${{ matrix.os }}
      buildArgs: ${{ matrix.buildArgs }}
      artifactName: ${{ matrix.artifactName }}
      artifactPath: ${{ matrix.artifactPath }}

  BuildAndroid:
    name: ${{ matrix.name }}
    if: ${{ inputs.buildAndroid }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Android x64
            os: macos-15
            buildArgs: "android -ONLY_ARM64"
            artifactName: Android x64
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
          - name: Android x32
            os: macos-15
            buildArgs: "android -ONLY_ARMV7"
            artifactName: Android x32
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
    uses: ./.github/workflows/build.yml
    with:
      name: ${{ matrix.name }}
      os: ${{ matrix.os }}
      buildArgs: ${{ matrix.buildArgs }}
      artifactName: ${{ matrix.artifactName }}
      artifactPath: ${{ matrix.artifactPath }}

  BuildIOS:
    name: iOS
    if: ${{ inputs.buildIOS }}
    uses: ./.github/workflows/build.yml
    with:
      name: iOS
      os: macos-15
      buildArgs: "ios -nosign"
      artifactName: IOS
      artifactPath: "export/release/ios/build/Release-iphoneos/*.ipa"
